version: "3.8"

services:
  nginx:
    build:
      context: ./Dockerfiles/nginx
    volumes:
        - wordpress_data:/var/www/html
        - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "443:443"
    networks:
      - wordpress_net
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: always
    entrypoint: ["/bin/bash", "-c", "/usr/local/bin/gcert.sh && nginx -g 'daemon off;'"]

  wordpress:
    build:
      context: ./Dockerfiles/wordpress
    environment:
      WORDPRESS_DB_HOST: ${WP_DB_HOST}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: adminpassword
      WORDPRESS_ADMIN_EMAIL: admin@example.com
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_net
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always

  mariadb:
    build:
      context: ./Dockerfiles/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${WP_DB_NAME}
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - wordpress_net
    restart: always

volumes:
  wordpress_data:
  mariadb_data:

networks:
  wordpress_net:
    driver: bridge