version: "3.8"

services:
  nginx:
    build:
      context: ./Dockerfiles/nginx
    volumes:
        - wordpress_data:/var/www/html
        - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "443:443"
    networks:
      - wordpress_net
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: always
    entrypoint: ["/bin/bash", "-c", "/usr/local/bin/gcert.sh && nginx -g 'daemon off;'"]

  wordpress:
    build:
      context: ./Dockerfiles/wordpress
    environment:
      WORDPRESS_DB_HOST: ${WP_DB_HOST}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
      WORDPRESS_DB_USER_: /run/secrets/wp_db_user
      WORDPRESS_DB_PASSWORD: /run/secrets/wp_db_password
      DOMAIN_NAME: ${DOMAIN_NAME}
      WORDPRESS_ADMIN_USER: /run/secrets/wp_admin
      WORDPRESS_ADMIN_PASSWORD: /run/secrets/wp_admin_password
      WORDPRESS_ADMIN_EMAIL: /run/secrets/wp_admin_email
      WORDPRESS_USER: /run/secrets/wp_user
      WORDPRESS_USER_PASSWORD: /run/secrets/wp_user_password
      WORDPRESS_USER_EMAIL: /run/secrets/wp_user_email
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_net
    depends_on:
      - mariadb
    secrets:
      - wp_db_user
      - wp_db_password
      - wp_admin_email
      - wp_admin
      - wp_admin_password
      - wp_user
      - wp_user_password
      - wp_user_email
    env_file:
      - .env
    restart: always

  mariadb:
    build:
      context: ./Dockerfiles/mariadb
    environment:
      MYSQL_DATABASE: ${WP_DB_NAME}
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - wordpress_net
    secrets:
      - wp_db_user
      - wp_db_password
      - db_root_password
    restart: always

secrets:
  wp_db_user:
    file: secrets/wp_db_user.txt
  wp_db_password:
    file: secrets/wp_db_user.txt
  db_root_password:
    file: secrets/db_root_password.txt
  wp_admin_email:
    file: secrets/wp_admin_email.txt
  wp_admin:
    file: secrets/wp_admin.txt
  wp_admin_password:
    file: secrets/wp_admin_password.txt
  wp_user:
    file: secrets/wp_user.txt
  wp_user_password:
    file: secrets/wp_user_password.txt
  wp_user_email:
    file: secrets/wp_user_email.txt

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/bbohle/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/bbohle/data/mariadb
      o: bind

networks:
  wordpress_net:
    driver: bridge